# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactSwiftUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactSwiftUI
  pod 'RxSwift'
  pod 'RxCocoa'

end

target 'ReactSwiftUIApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactSwiftUIApp
  pod 'RxSwift'
  pod 'RxCocoa'
end
